feature/input_copy_chrExt
WithCodeTeam/Extension pull request #4
Opened 2017-07-10 11:49 UTC by Wojtekkas

2017-07-11 04:03 UTC, MKwestorowski commented on extension/mtu.js
> +        var nameValue = request.nameValue
What request doing here? Is this method from chrome function? Please explain

2017-07-11 04:05 UTC, MKwestorowski commented on extension/popup.html
> +      <input id="licenseDate" placeholder="__-__-____" type="date"/>
There we need validation, please try to do it before merge to develop. Same thing happens in 61 line. Good Luck :) !

2017-07-11 04:09 UTC, MKwestorowski commented on extension/mtu.js
> +        if (licenseValue)
I cant get this if, is this thing doing something here? I think this isn't, may I'm dumb. Please explain.

2017-07-11 04:12 UTC, MKwestorowski approved these changes
Im fine with this, anyway i want to know why we need this vcs.xml. I think we should make some css file to style popup. Look at line comments, if u can explain some thing today, at daily. This should be great. Have good time ! :)

2017-07-11 22:39 UTC, Wojtekkas commented on extension/mtu.js
> +        if (licenseValue)
fixed

2017-07-11 22:43 UTC, Wojtekkas commented on extension/popup.html
> +      <input id="licenseDate" placeholder="__-__-____" type="date"/>
Validation is on our todo list. I will do it later.

2017-07-11 23:00 UTC, Wojtekkas commented on extension/mtu.js
> +        var nameValue = request.nameValue
Request is for communicating between content script and extension. You need to use request if u want to handle the message that had been sent to you from one of this two above mentioned.

2017-07-12 11:53 UTC, falbor45 requested changes
Other than removal of .idea/vcs.xml file and changing id names into a proper camelCase notation (@popup.html #L(37/41/47/51) & @popup.js #L2), I have no objections, yet I'd rather have it done before upcoming merge so that we don't leave ourselves with excessive amount of redundant files on that very branch.

2017-07-16 21:24 UTC, RafalPaluch commented on extension/mtu.js
> +        var nameValue = request.nameValue
You mean of couse by extension background scripts

2017-07-16 21:24 UTC, RafalPaluch commented on extension/manifest.json
>    },
Can we treat content script and background script as the same file. I mean mtu.js. I though content script deal with other things than background script and these 2 files should coummunicate with each other etc. Please explain.( I do not mark this line, please open the file)

2017-07-17 16:13 UTC, RafalPaluch commented on extension/popup.js
>  }
Is this function necessery?

2017-07-17 16:13 UTC, RafalPaluch commented on extension/popup.js
>  },false);
Is that addeventListener necessery? Like above function it only gets Nameimput variable, so i guess whole  script should work wothout it.  Please explain.

2017-07-19 20:15 UTC, MKwestorowski commented on extension/popup.js
>  }
This function is necessery, absolute. This lines, setting value of current input.

2017-07-19 20:20 UTC, MKwestorowski commented on extension/popup.js
>  },false);
U must set listeners on document to look for findExtInput and also nameInput. Then we have to do something if someone is typing in current input. Thats why its `currentInput.onchange`
If someone change content of input areas this line call out updateInput function. That last one function is explained above this post.

2017-07-20 04:53 UTC, RafalPaluch commented on extension/popup.js
>  }
Not current. Only one input. That's why I asked. Try to delete it and find the differences.

2017-07-20 04:53 UTC, RafalPaluch commented on extension/popup.js
>  },false);
Line with FindeExtInput is actually deleted. I know even by name what the function is doing :). Please go above this post. The question is valid for this line also. Thanks anyway for answer:)))

2017-07-20 15:42 UTC, MKwestorowski commented on extension/popup.js
>  }
Take look at next pull request by Artur. This functions were fixed by adding another tags with ids. Have a look at deleted line. There was a random input name. Now changed at unique that present name.

2017-07-20 19:36 UTC, RafalPaluch commented on extension/popup.js
>  }
...

2017-07-23 10:42 UTC, merged