Merge store data feature into main extension branch
WithCodeTeam/Extension pull request #6
Opened 2017-07-12 11:55 UTC by falbor45

2017-07-12 15:52 UTC, MKwestorowski requested changes

2017-07-12 15:52 UTC, MKwestorowski commented on extension/popup.js
> +    localStorage.setItem('name', event.target.value)
I think there start a problem. If somebody wrote incorrect data, that gonna be incorrect at another places. May we should try to validate before set to storage. What do u think?

2017-07-12 15:52 UTC, MKwestorowski commented on extension/popup.js
> +        if (selectAllInputs[i].type == 'text' || selectAllInputs[i].type == 'number') {
Why do You here using two equals signs? Another future is what type means? I looked for some mdm documentation but got only .type() in jQuery. If u mean typeof there isn't thing like text. I hope u mean string 💃 . Have fun!

2017-07-12 15:58 UTC, falbor45 commented on extension/popup.js
> +        if (selectAllInputs[i].type == 'text' || selectAllInputs[i].type == 'number') {
You are absolutely right. ".type" is not a function that exists solely in bounds of Javascript itself. ".type" is a Web API function and is the most efficient way to find out control form's type I have found so far. If you try to console.log any of the iterrated elements, you will see either 'text', 'number', or 'date' as an output. :) 
TLDR;
'.type' is all good, and AFAIK the most efficient way, it is not related to jQuery at all (in this very situation)

2017-07-12 22:01 UTC, Wojtekkas commented on extension/popup.js
> +    localStorage.setItem('name', event.target.value)
We can validate inputs just by using simple patterns like=[A-Za-z] but we cant prevent users from making typo in name.

2017-07-12 22:35 UTC, Wojtekkas commented on extension/popup.js
> +    var selectAllInputs = document.getElementsByTagName('input')
We need to be careful here. We got a permission to all tabs so we will erase all user inputs and we dont want to do it.

2017-07-12 22:40 UTC, Wojtekkas approved these changes
Looks okay to me.

Just think about the line 86.

2017-07-13 07:09 UTC, falbor45 commented on extension/popup.js
> +    var selectAllInputs = document.getElementsByTagName('input')
It will clean only the inputs inside the extension as it is treated as a completely separate document.

2017-07-15 04:11 UTC, MKwestorowski approved these changes

2017-07-16 18:58 UTC, RafalPaluch commented on extension/popup.js
> +
This is the good place for refactoring. Now its Ok, but for sure the will be more lines like this in this section.

2017-07-16 18:58 UTC, RafalPaluch commented on extension/popup.js
> +    localStorage.setItem('name', event.target.value)
For sure,we need validation for  Zip Code etc. to prevent use O instead of 0 etc

2017-07-16 19:06 UTC, RafalPaluch approved these changes
Ok

2017-07-16 19:08 UTC, RafalPaluch approved these changes

2017-07-23 10:42 UTC, merged